# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0a512a755dead3bbe44b85c8b880989fb4c36845d580c7323c51e655fb85643566d3fe20d55e9c21e0499df9bb6b34e6ce3ea29cc7b7a67c5b7eabad19fdb2ac

test:
  secret_key_base: 258061ed5c335e5f3d768fd51469c8ba795895b1e247e7a3210e8d72713aedb03efb1e49050d20f806b65289053a5b82a99805b157db9ff5e04d6a707b7cf581

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
